const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const client=window.supabase?.createClient(window.WOODRI_SUPABASE_URL,window.WOODRI_SUPABASE_KEY);
const toggle=$('.menu-toggle'),nav=$('.nav-links'); toggle?.addEventListener('click',()=>nav?.classList.toggle('open'));
$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.toggle('active',x===b));$$('.catalog-card').forEach(c=>c.hidden=b.dataset.filter!=='all'&&c.dataset.category!==b.dataset.filter)}));
async function rows(table, published=true){if(!client)return [];let q=client.from(table).select('*');if(published&&table!=='vouchers')q=q.eq('is_published',true);const {data,error}=await q.order('created_at',{ascending:false});if(error){console.error(error);return []}return data||[]}
async function setting(key){if(!client)return null;const {data}=await client.from('site_settings').select('value').eq('key',key).maybeSingle();return data?.value||null}
function setNotice(form,msg){const box=$('.success',form);if(box){box.style.display='block';box.textContent=msg}}
async function renderPublic(){if(!client)return;
  const [products,stories,logos,posts,promo,copy,vouchers]=await Promise.all([rows('products'),rows('testimonials'),rows('partners'),rows('posts'),setting('promo'),setting('copy'),rows('vouchers')]);
  const logoArea=$('#client-logos');if(logoArea&&logos.length)logoArea.innerHTML=logos.map(x=>`<b class="managed-logo">${x.logo?`<img src="${esc(x.logo)}" alt="Logo ${esc(x.name)}">`:''}${esc(x.name)}</b>`).join('');
  if(copy){for(const [key,selector] of Object.entries({headline:'[data-copy="headline"]',description:'[data-copy="description"]',subheadline:'[data-copy="subheadline"]'})){const el=$(selector);if(el&&copy[key])el.textContent=copy[key]}}
  const tb=$('#testimonials');if(tb&&stories.length)tb.innerHTML=stories.map(x=>`<article class="story-card"><div class="org-logo">${x.logo?`<img src="${esc(x.logo)}" alt="Logo ${esc(x.name)}" style="max-width:110px;max-height:40px;object-fit:contain">`:esc(x.name)}</div><blockquote>“${esc(x.quote)}”</blockquote><small>${esc(x.name)}</small></article>`).join('');
  const bp=$('#blog-posts');if(bp&&posts.length)bp.innerHTML=posts.map(x=>`<article class="journal-card">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.title)}">`:''}<div><small>${esc(x.category||'Woodri Journal')}</small><h3>${esc(x.title)}</h3><p>${esc(x.excerpt||'')}</p>${x.content?`<details><summary>Baca artikel</summary><p>${esc(x.content).replace(/\n/g,'<br>')}</p></details>`:''}</div></article>`).join('');
  const cg=$('.catalog-grid');if(cg&&location.pathname.endsWith('katalog.html')&&products.length){$$('.catalog-card[data-managed]').forEach(x=>x.remove());for(const p of products){const c=document.createElement('article');c.className='catalog-card';c.dataset.category=(p.category||'custom').toLowerCase();c.dataset.managed='true';c.innerHTML=`${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:'<div class="product-placeholder">WOODRI · CUSTOM</div>'}<div><small>${esc(p.category)}</small><h3>${esc(p.name)}</h3><p>${esc(p.description||'Produk dapat disesuaikan berdasarkan kebutuhan proyek.')}</p><a href="kontak.html">Tanyakan opsi custom ↗</a><details><summary>Detail bahan & spesifikasi</summary><div class="spec-list"><b>Bahan</b><span>${esc(p.materials||'Konsultasikan')}</span><b>Spesifikasi</b><span>${esc(p.specs||'Custom sesuai brief')}</span></div></details></div>`;cg.append(c)}}
  const announcement=$('.announcement');if(announcement&&promo?.banner)announcement.innerHTML=`${esc(promo.banner)} <span>✳</span> <a href="wizard.html">${esc(promo.cta||'Rencanakan hadiah')} ↗</a>`;
  const voucher=vouchers.find(v=>v.is_active);window.WOODRI_ACTIVE_VOUCHER=voucher||null;
}
const contact=$('.contact-form:not(.wizard-form)');contact?.addEventListener('submit',async e=>{e.preventDefault();if(!client)return setNotice(contact,'Form belum terhubung ke database. Silakan hubungi kami melalui WhatsApp.');const v=Object.fromEntries(new FormData(contact));const {error}=await client.from('leads').insert({name:v.nama,email:v.email,company:v.perusahaan,source:'contact',event:v.kebutuhan,details:v.pesan,consent:true});if(error){console.error(error);return setNotice(contact,'Pesan belum terkirim. Silakan coba lagi atau hubungi kami melalui WhatsApp.')}setNotice(contact,'Terima kasih. Permintaan Anda sudah tercatat dan tim Woodri akan menindaklanjuti.');const msg=`Halo Woodri, saya ${v.nama}${v.perusahaan?' dari '+v.perusahaan:''}. Email: ${v.email}. Kebutuhan: ${v.kebutuhan}. Pesan: ${v.pesan}`;window.open(`https://wa.me/6289647188725?text=${encodeURIComponent(msg)}`,'_blank','noopener');contact.reset()});
const wizard=$('.wizard-form');wizard?.addEventListener('submit',async e=>{e.preventDefault();if(!client)return setNotice(wizard,'Form belum terhubung. Silakan hubungi tim Woodri melalui WhatsApp.');const v=Object.fromEntries(new FormData(wizard));const voucher=window.WOODRI_ACTIVE_VOUCHER;if(!voucher)return setNotice(wizard,'Voucher belum tersedia. Tim Woodri dapat membantu Anda memilih penawaran yang aktif.');const {error}=await client.from('leads').insert({name:v.nama,email:v.email,company:v.perusahaan,whatsapp:v.whatsapp,source:'gift planner',event:v.acara,material:v.material,quantity:v.kuantitas,needed_on:v.tanggal||null,details:v.detail,voucher_code:voucher.code,consent:true});if(error){console.error(error);return setNotice(wizard,'Data belum tersimpan. Silakan coba lagi.')}const box=$('#wizard-success');box.style.display='block';box.innerHTML=`<strong>Voucher Anda: ${esc(voucher.code)}</strong><br>Diskon ${esc(voucher.discount)}%${voucher.expires_on?' · Berlaku sampai '+esc(voucher.expires_on):''}. Tim Woodri akan menghubungi Anda untuk melanjutkan kurasi hadiah.<br><a href="https://wa.me/6289647188725?text=${encodeURIComponent(`Halo Woodri, saya ${v.nama} dari ${v.perusahaan}. Saya sudah mengisi Gift Planner dan ingin konsultasi. Kode voucher ${voucher.code}.`)}" target="_blank" rel="noreferrer">Konfirmasi melalui WhatsApp ↗</a>`;wizard.reset();box.scrollIntoView({behavior:'smooth',block:'center'})});

const admin=$('#admin-app');
async function initAdmin(){if(!admin||!client)return;const login=$('#admin-login'),workspace=$('#admin-workspace'),message=$('#login-message');const {data:{session}}=await client.auth.getSession();if(session){const {data}=await client.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();if(data){login.hidden=true;workspace.hidden=false;await renderAdmin();return}await client.auth.signOut();message.textContent='Akun ini belum diberi akses admin.'}
  login.hidden=false;workspace.hidden=true;$('#login-form').addEventListener('submit',async e=>{e.preventDefault();message.textContent='Memeriksa akun…';const fd=new FormData(e.currentTarget);const {error}=await client.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error){message.textContent='Login gagal. Periksa email dan kata sandi.';return}location.reload()});$('#google-sso')?.addEventListener('click',async()=>{message.textContent='Menghubungkan ke Google…';const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href}});if(error)message.textContent='SSO Google belum tersedia. Aktifkan Google provider di Supabase, atau gunakan login email.'});$('#admin-logout').addEventListener('click',async()=>{await client.auth.signOut();location.reload()});
}
const tables={products:'products',stories:'testimonials',logos:'partners',posts:'posts'};
function drawList(id,items){const el=$('#'+id);if(!el)return;const table=({'product-list':'products','story-list':'testimonials','logo-list':'partners','blog-list':'posts'})[id];el.innerHTML=items.map(x=>`<div class="admin-item"><span><b>${esc(x.name||x.title)}</b> · ${esc(x.category||x.materials||x.quote||'')}</span><span><button data-edit-table="${esc(table)}" data-id="${x.id}">Edit</button><button data-delete="${esc(table)}" data-id="${x.id}">Hapus</button></span></div>`).join('')||'<div class="notice">Belum ada entri.</div>'}
async function renderAdmin(){const [leads,products,stories,logos,posts,promo,copy,vouchers]=await Promise.all([rows('leads',false),rows('products',false),rows('testimonials',false),rows('partners',false),rows('posts',false),setting('promo'),setting('copy'),rows('vouchers',false)]);const date=$('#admin-date');if(date)date.textContent=new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('#lead-count').textContent=leads.length;$('#product-count').textContent=products.length;$('#voucher-code').textContent=vouchers.find(v=>v.is_active)?.code||'—';$('#lead-list').innerHTML=leads.map(x=>`<article class="lead-item"><b>${esc(x.name)}</b> · ${esc(x.company)}<small>${esc(x.email)} · ${esc(x.whatsapp)} · ${new Date(x.created_at).toLocaleString('id-ID')}</small>Kebutuhan: ${esc(x.event)} | Material: ${esc(x.material)} | Kuantitas: ${esc(x.quantity)}<br>${esc(x.details)}</article>`).join('')||'<div class="notice">Belum ada prospek.</div>';drawList('product-list',products);drawList('story-list',stories);drawList('logo-list',logos);drawList('blog-list',posts);
  const pf=$('#promo-form');if(pf&&promo){pf.elements.banner.value=promo.banner||'';pf.elements.cta.value=promo.cta||'';const v=vouchers.find(x=>x.is_active);if(v){pf.elements.code.value=v.code;pf.elements.discount.value=v.discount;pf.elements.expiry.value=v.expires_on||''}}
  const cf=$('#copy-form');if(cf&&copy)for(const [k,v] of Object.entries(copy))if(cf.elements[k])cf.elements[k].value=v;
}
async function saveForm(id,table,transform=v=>v){const f=$('#'+id);if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const value=transform(Object.fromEntries(new FormData(f)));const editId=f.dataset.editId;const result=editId?await client.from(table).update(value).eq('id',editId):await client.from(table).insert(value);if(result.error){console.error(result.error);return setNotice(f,'Tidak tersimpan. Periksa data lalu coba lagi.')}delete f.dataset.editId;f.reset();const button=$('button[type="submit"]',f);if(button?.dataset.originalText){button.innerHTML=button.dataset.originalText;delete button.dataset.originalText}await renderAdmin();await renderPublic()})}
if(admin){initAdmin().then(()=>{if($('#promo-form')){
  saveForm('product-form','products');saveForm('story-form','testimonials');saveForm('logo-form','partners');saveForm('blog-form','posts');
  $('#promo-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,v=Object.fromEntries(new FormData(f));const {error:se}=await client.from('site_settings').upsert({key:'promo',value:{banner:v.banner,cta:v.cta},updated_at:new Date().toISOString()});if(se)return setNotice(f,'Banner belum tersimpan.');await client.from('vouchers').update({is_active:false}).eq('is_active',true);const {error:ve}=await client.from('vouchers').insert({code:v.code.toUpperCase(),discount:Number(v.discount)||0,expires_on:v.expiry||null,is_active:true});if(ve){console.error(ve);return setNotice(f,'Banner tersimpan, tetapi voucher gagal diperbarui. Pastikan kodenya unik.')}setNotice(f,'Banner dan voucher tersimpan.');await renderAdmin();await renderPublic()});
  $('#copy-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,v=Object.fromEntries(new FormData(f));const {error}=await client.from('site_settings').upsert({key:'copy',value:v,updated_at:new Date().toISOString()});setNotice(f,error?'Teks belum tersimpan.':'Teks website tersimpan.');await renderPublic()});
  document.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit-table]');if(edit){const formId=({'products':'product-form','testimonials':'story-form','partners':'logo-form','posts':'blog-form'})[edit.dataset.editTable],form=$('#'+formId);const {data,error}=await client.from(edit.dataset.editTable).select('*').eq('id',edit.dataset.id).single();if(error||!form)return alert('Data tidak berhasil dibuka untuk diedit.');for(const field of form.elements)if(field.name&&data[field.name]!=null)field.value=data[field.name];form.dataset.editId=data.id;const submit=$('button[type="submit"]',form);if(submit){submit.dataset.originalText||=submit.innerHTML;submit.innerHTML='Simpan perubahan <span>→</span>'}form.scrollIntoView({behavior:'smooth',block:'center'});return}const b=e.target.closest('[data-delete]');if(!b||!confirm('Hapus item ini?'))return;const {error}=await client.from(b.dataset.delete).delete().eq('id',b.dataset.id);if(error)alert('Data tidak berhasil dihapus.');else await renderAdmin()});
}})}
renderPublic();
// A short branded loading veil prevents partially styled pages from flashing.
function finishLoading(){document.body.classList.add('is-ready');setTimeout(()=>$('.site-loader')?.remove(),550)}
if(document.readyState==='complete')finishLoading();else window.addEventListener('load',finishLoading,{once:true});
setTimeout(finishLoading,1800);
if('IntersectionObserver'in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.12});$$('body:not(.admin-body) main>section').forEach(el=>{el.classList.add('reveal');observer.observe(el)})}
